services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ganesh-chanda-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "GaneshChanda@2026!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ganesh_chanda_sql:/var/opt/mssql

volumes:
  ganesh_chanda_sql:
